#define BezierEdge                    	 _MMG5_BezierEdge
#define BezierGeod                    	 _MMG5_BezierGeod
#define BezierNom                     	 _MMG5_BezierNom
#define BezierRef                     	 _MMG5_BezierRef
#define BezierReg                     	 _MMG5_BezierReg
#define BezierRidge                   	 _MMG5_BezierRidge
#define BezierTgt                     	 _MMG5_BezierTgt
#define DoSol                         	 _MMG5_DoSol
#define addBucket                     	 _MMG5_addBucket
#define analys                        	 _MMG5_analys
#define badelt                        	 _MMG5_badelt
#define bdryIso                       	 _MMG5_bdryIso
#define bdryPerm                      	 _MMG5_bdryPerm
#define bdrySet                       	 _MMG5_bdrySet
#define bdryTria                      	 _MMG5_bdryTria
#define bdryUpdate                    	 _MMG5_bdryUpdate
#define bdyMCF                        	 _MMG5_bdyMCF
#define bezierCP                      	 _MMG5_bezierCP
#define bezierInt                     	 _MMG5_bezierInt
#define boulec                        	 _MMG5_boulec
#define bouleext                      	 _MMG5_bouleext
#define boulen                        	 _MMG5_boulen
#define boulenm                       	 _MMG5_boulenm
#define bouler                        	 _MMG5_bouler
#define boulesurfvolp                 	 _MMG5_boulesurfvolp
#define boulevolp                     	 _MMG5_boulevolp
#define buckin_iso                    	 _MMG5_buckin_iso
#define caltet_ani                    	 _MMG5_caltet_ani
#define caltet_iso                    	 _MMG5_caltet_iso
#define caltri                        	 _MMG5_caltri
#define cavity                        	 _MMG5_cavity
#define cenrad_iso                    	 _MMG5_cenrad_iso
#define chkcol_bdy                    	 _MMG5_chkcol_bdy
#define chkcol_int                    	 _MMG5_chkcol_int
#define chkedg                        	 _MMG5_chkedg
#define chkfemtopo                    	 _MMG5_chkfemtopo
#define chkmani                       	 _MMG5_chkmani
#define chkmanicoll                   	 _MMG5_chkmanicoll
#define chkmsh                        	 _MMG5_chkmsh
#define chkptonbdy                    	 _MMG5_chkptonbdy
#define chkswpbdy                     	 _MMG5_chkswpbdy
#define chkswpgen                     	 _MMG5_chkswpgen
#define cntbdypt                      	 _MMG5_cntbdypt
#define colver                        	 _MMG5_colver
#define coquil                        	 _MMG5_coquil
#define coquilface                    	 _MMG5_coquilface
#define defsiz_ani                    	 _MMG5_defsiz_ani
#define defsiz_iso                    	 _MMG5_defsiz_iso
#define delBucket                     	 _MMG5_delBucket
#define delElt                        	 _MMG5_delElt
#define delPt                         	 _MMG5_delPt
#define delone                        	 _MMG5_delone
#define denoisbdy                     	 _MMG5_denoisbdy
#define det3pt1vec                    	 _MMG5_det3pt1vec
#define det4pt                        	 _MMG5_det4pt
#define dichodisp                     	 _MMG5_dichodisp
#define dichoto1b                     	 _MMG5_dichoto1b
#define directsurfball                	 _MMG5_directsurfball
#define eigensym                      	 _MMG5_eigensym
#define freeBucket                    	 _MMG5_freeBucket
#define freeXTets                     	 _MMG5_freeXTets
#define gettag                        	 _MMG5_gettag
#define gradsiz_ani                   	 _MMG5_gradsiz_ani
#define gradsiz_iso                   	 _MMG5_gradsiz_iso
#define hEdge                         	 _MMG5_hEdge
#define hGeom                         	 _MMG5_hGeom
#define hGet                          	 _MMG5_hGet
#define hNew                          	 _MMG5_hNew
#define hPop                          	 _MMG5_hPop
#define hTag                          	 _MMG5_hTag
#define hashEdge                      	 _MMG5_hashEdge
#define hashGet                       	 _MMG5_hashGet
#define hashNew                       	 _MMG5_hashNew
#define hashPop                       	 _MMG5_hashPop
#define hashTetra                     	 _MMG5_hashTetra
#define hashTria                      	 _MMG5_hashTria
#define lapantilap                    	 _MMG5_lapantilap
#define lenedg_ani                    	 _MMG5_lenedg_ani
#define lenedg_iso                    	 _MMG5_lenedg_iso
#define meancur                       	 _MMG5_meancur
#define mmg3d1                        	 _MMG5_mmg3d1
#define mmg3d1_delone                 	 _MMG5_mmg3d1_delone
#define mmg3d2                        	 _MMG5_mmg3d2
#define movbdynompt                   	 _MMG5_movbdynompt
#define movbdyrefpt                   	 _MMG5_movbdyrefpt
#define movbdyregpt                   	 _MMG5_movbdyregpt
#define movbdyridpt                   	 _MMG5_movbdyridpt
#define movintpt                      	 _MMG5_movintpt
#define newBucket                     	 _MMG5_newBucket
#define newElt                        	 _MMG5_newElt
#define newPt                         	 _MMG5_newPt
#define norface                       	 _MMG5_norface
#define norpts                        	 _MMG5_norpts
#define nortri                        	 _MMG5_nortri
#define nsort                         	 _MMG5_nsort
#define orcal                         	 _MMG5_orcal
#define orcal_poi                     	 _MMG5_orcal_poi
#define orvol                         	 _MMG5_orvol
#define outqua                        	 _MMG5_outqua
#define ppgdisp                       	 _MMG5_ppgdisp
#define prilen                        	 _MMG5_prilen
#define renumbering                   	 _MMG5_renumbering
#define rotmatrix                     	 _MMG5_rotmatrix
#define scaleMesh                     	 _MMG5_scaleMesh
#define settag                        	 _MMG5_settag
#define simbulgept                    	 _MMG5_simbulgept
#define split1                        	 _MMG5_split1
#define split1_sim                    	 _MMG5_split1_sim
#define split1b                       	 _MMG5_split1b
#define split2                        	 _MMG5_split2
#define split2sf                      	 _MMG5_split2sf
#define split2sf_sim                  	 _MMG5_split2sf_sim
#define split3                        	 _MMG5_split3
#define split3_sim                    	 _MMG5_split3_sim
#define split3cone                    	 _MMG5_split3cone
#define split3op                      	 _MMG5_split3op
#define split4bar                     	 _MMG5_split4bar
#define split4op                      	 _MMG5_split4op
#define split4sf                      	 _MMG5_split4sf
#define split5                        	 _MMG5_split5
#define split6                        	 _MMG5_split6
#define srcbdy                        	 _MMG5_srcbdy
#define srcface                       	 _MMG5_srcface
#define startedgsurfball              	 _MMG5_startedgsurfball
#define surftri                       	 _MMG5_surftri
#define swpbdy                        	 _MMG5_swpbdy
#define swpgen                        	 _MMG5_swpgen
#define sys33sym                      	 _MMG5_sys33sym
#define tet2tri                       	 _MMG5_tet2tri
#define timestepMCF                   	 _MMG5_timestepMCF
#define trydisp                       	 _MMG5_trydisp
#define unscaleMesh                   	 _MMG5_unscaleMesh
#define volint                        	 _MMG5_volint
#define zaldy                         	 _MMG5_zaldy
#define loadMesh                      	 MMG5_loadMesh
#define loadMet                       	 MMG5_loadMet
#define mmg3dinit                     	 MMG5_mmg3dinit
#define mmg3dlib                      	 MMG5_mmg3dlib
#define saveMesh                      	 MMG5_saveMesh
#define saveMet                       	 MMG5_saveMet
#define stockOption                   	 MMG5_stockOption
