#define BezierEdge                    	 _MMG5_BezierEdge
#define BezierGeod                    	 _MMG5_BezierGeod
#define BezierNom                     	 _MMG5_BezierNom
#define BezierRef                     	 _MMG5_BezierRef
#define BezierReg                     	 _MMG5_BezierReg
#define BezierRidge                   	 _MMG5_BezierRidge
#define BezierTgt                     	 _MMG5_BezierTgt
#define DoSol                         	 _MMG5_DoSol
#define _MMG5_saveAllMesh             	 _MMG5__MMG5_saveAllMesh
#define _MMG5_saveLibraryMesh         	 _MMG5__MMG5_saveLibraryMesh
#define addBucket                     	 _MMG5_addBucket
#define analys                        	 _MMG5_analys
#define anatet                        	 _MMG5_anatet
#define anatet4                       	 _MMG5_anatet4
#define anatets                       	 _MMG5_anatets
#define arpt                          	 _MMG5_arpt
#define badelt                        	 _MMG5_badelt
#define bdryIso                       	 _MMG5_bdryIso
#define bdryPerm                      	 _MMG5_bdryPerm
#define bdrySet                       	 _MMG5_bdrySet
#define bdryTria                      	 _MMG5_bdryTria
#define bdryUpdate                    	 _MMG5_bdryUpdate
#define bdyMCF                        	 _MMG5_bdyMCF
#define bezierCP                      	 _MMG5_bezierCP
#define bezierInt                     	 _MMG5_bezierInt
#define boulec                        	 _MMG5_boulec
#define bouleext                      	 _MMG5_bouleext
#define boulen                        	 _MMG5_boulen
#define boulenm                       	 _MMG5_boulenm
#define bouler                        	 _MMG5_bouler
#define boulesurfvolp                 	 _MMG5_boulesurfvolp
#define boulevolp                     	 _MMG5_boulevolp
#define buckin_iso                    	 _MMG5_buckin_iso
#define caltet_ani                    	 _MMG5_caltet_ani
#define caltet_iso                    	 _MMG5_caltet_iso
#define caltri                        	 _MMG5_caltri
#define cavity                        	 _MMG5_cavity
#define cenrad_iso                    	 _MMG5_cenrad_iso
#define chkNumberOfTri                	 _MMG5_chkNumberOfTri
#define chkcol_bdy                    	 _MMG5_chkcol_bdy
#define chkcol_int                    	 _MMG5_chkcol_int
#define chkedg                        	 _MMG5_chkedg
#define chkedg                        	 _MMG5_chkedg
#define chkfemtopo                    	 _MMG5_chkfemtopo
#define chkmani                       	 _MMG5_chkmani
#define chkmanicoll                   	 _MMG5_chkmanicoll
#define chkmsh                        	 _MMG5_chkmsh
#define chkptonbdy                    	 _MMG5_chkptonbdy
#define chkswpbdy                     	 _MMG5_chkswpbdy
#define chkswpgen                     	 _MMG5_chkswpgen
#define cntbdypt                      	 _MMG5_cntbdypt
#define colSing                       	 _MMG5_colSing
#define coltet                        	 _MMG5_coltet
#define colver                        	 _MMG5_colver
#define coquil                        	 _MMG5_coquil
#define coquilface                    	 _MMG5_coquilface
#define countelt                      	 _MMG5_countelt
#define creaEdge                      	 _MMG5_creaEdge
#define creaPoint                     	 _MMG5_creaPoint
#define defsiz_ani                    	 _MMG5_defsiz_ani
#define defsiz_iso                    	 _MMG5_defsiz_iso
#define delBucket                     	 _MMG5_delBucket
#define delElt                        	 _MMG5_delElt
#define delPt                         	 _MMG5_delPt
#define delone                        	 _MMG5_delone
#define denoisbdy                     	 _MMG5_denoisbdy
#define det3pt1vec                    	 _MMG5_det3pt1vec
#define det4pt                        	 _MMG5_det4pt
#define dichodisp                     	 _MMG5_dichodisp
#define dichoto                       	 _MMG5_dichoto
#define dichoto1b                     	 _MMG5_dichoto1b
#define dichoto1b                     	 _MMG5_dichoto1b
#define directsurfball                	 _MMG5_directsurfball
#define eigensym                      	 _MMG5_eigensym
#define freeXTets                     	 _MMG5_freeXTets
#define gettag                        	 _MMG5_gettag
#define gradsiz_ani                   	 _MMG5_gradsiz_ani
#define gradsiz_iso                   	 _MMG5_gradsiz_iso
#define hEdge                         	 _MMG5_hEdge
#define hGeom                         	 _MMG5_hGeom
#define hGet                          	 _MMG5_hGet
#define hNew                          	 _MMG5_hNew
#define hPop                          	 _MMG5_hPop
#define hTag                          	 _MMG5_hTag
#define hashEdge                      	 _MMG5_hashEdge
#define hashGet                       	 _MMG5_hashGet
#define hashNew                       	 _MMG5_hashNew
#define hashPop                       	 _MMG5_hashPop
#define hashTetra                     	 _MMG5_hashTetra
#define hashTria                      	 _MMG5_hashTria
#define iare                          	 _MMG5_iare
#define iarf                          	 _MMG5_iarf
#define iarfinv                       	 _MMG5_iarfinv
#define idir                          	 _MMG5_idir
#define idirinv                       	 _MMG5_idirinv
#define ifar                          	 _MMG5_ifar
#define indElt                        	 _MMG5_indElt
#define indPt                         	 _MMG5_indPt
#define inserSingul                   	 _MMG5_inserSingul
#define inxt2                         	 _MMG5_inxt2
#define inxt3                         	 _MMG5_inxt3
#define iprv2                         	 _MMG5_iprv2
#define iprv3                         	 _MMG5_iprv3
#define isar                          	 _MMG5_isar
#define lapantilap                    	 _MMG5_lapantilap
#define lenedgCoor_ani                	 _MMG5_lenedgCoor_ani
#define lenedgCoor_iso                	 _MMG5_lenedgCoor_iso
#define lenedg_ani                    	 _MMG5_lenedg_ani
#define lenedg_iso                    	 _MMG5_lenedg_iso
#define meancur                       	 _MMG5_meancur
#define memOption                     	 _MMG5_memOption
#define memSize                       	 _MMG5_memSize
#define mmg3d1                        	 _MMG5_mmg3d1
#define mmg3d1_delone                 	 _MMG5_mmg3d1_delone
#define mmg3d2                        	 _MMG5_mmg3d2
#define movbdynompt                   	 _MMG5_movbdynompt
#define movbdyrefpt                   	 _MMG5_movbdyrefpt
#define movbdyregpt                   	 _MMG5_movbdyregpt
#define movbdyridpt                   	 _MMG5_movbdyridpt
#define movintpt                      	 _MMG5_movintpt
#define newBucket                     	 _MMG5_newBucket
#define newElt                        	 _MMG5_newElt
#define newPt                         	 _MMG5_newPt
#define norface                       	 _MMG5_norface
#define norpts                        	 _MMG5_norpts
#define nortri                        	 _MMG5_nortri
#define nsort                         	 _MMG5_nsort
#define orcal                         	 _MMG5_orcal
#define orcal_poi                     	 _MMG5_orcal_poi
#define orvol                         	 _MMG5_orvol
#define outqua                        	 _MMG5_outqua
#define ppgdisp                       	 _MMG5_ppgdisp
#define prilen                        	 _MMG5_prilen
#define printTetra                    	 _MMG5_printTetra
#define printTria                     	 _MMG5_printTria
#define renumbering                   	 _MMG5_renumbering
#define rotmatrix                     	 _MMG5_rotmatrix
#define scaleMesh                     	 _MMG5_scaleMesh
#define seekEdge                      	 _MMG5_seekEdge
#define seekPoint                     	 _MMG5_seekPoint
#define settag                        	 _MMG5_settag
#define simbulgept                    	 _MMG5_simbulgept
#define solveUnsignedTet              	 _MMG5_solveUnsignedTet
#define split1                        	 _MMG5_split1
#define split1_sim                    	 _MMG5_split1_sim
#define split1b                       	 _MMG5_split1b
#define split2                        	 _MMG5_split2
#define split2sf                      	 _MMG5_split2sf
#define split2sf_sim                  	 _MMG5_split2sf_sim
#define split3                        	 _MMG5_split3
#define split3_sim                    	 _MMG5_split3_sim
#define split3cb                      	 _MMG5_split3cb
#define split3cone                    	 _MMG5_split3cone
#define split3op                      	 _MMG5_split3op
#define split4bar                     	 _MMG5_split4bar
#define split4cb                      	 _MMG5_split4cb
#define split4op                      	 _MMG5_split4op
#define split4sf                      	 _MMG5_split4sf
#define split5                        	 _MMG5_split5
#define split6                        	 _MMG5_split6
#define srcbdy                        	 _MMG5_srcbdy
#define srcface                       	 _MMG5_srcface
#define startedgsurfball              	 _MMG5_startedgsurfball
#define surftri                       	 _MMG5_surftri
#define swap23                        	 _MMG5_swap23
#define swpbdy                        	 _MMG5_swpbdy
#define swpbdy                        	 _MMG5_swpbdy
#define swpgen                        	 _MMG5_swpgen
#define swpgen                        	 _MMG5_swpgen
#define swpmsh                        	 _MMG5_swpmsh
#define sys33sym                      	 _MMG5_sys33sym
#define tet2tri                       	 _MMG5_tet2tri
#define tet2tri                       	 _MMG5_tet2tri
#define timestepMCF                   	 _MMG5_timestepMCF
#define trydisp                       	 _MMG5_trydisp
#define unscaleMesh                   	 _MMG5_unscaleMesh
#define volint                        	 _MMG5_volint
#define zaldy                         	 _MMG5_zaldy
#define Chk_meshData                  	 MMG5_Chk_meshData
#define Edge                          	 MMG5_Edge
#define Free_all                      	 MMG5_Free_all
#define Free_all                      	 MMG5_Free_all
#define Free_names                    	 MMG5_Free_names
#define Free_names                    	 MMG5_Free_names
#define Free_structures               	 MMG5_Free_structures
#define Free_structures               	 MMG5_Free_structures
#define Get_adjaTet                   	 MMG5_Get_adjaTet
#define Get_edge                      	 MMG5_Get_edge
#define Get_meshSize                  	 MMG5_Get_meshSize
#define Get_scalarSol                 	 MMG5_Get_scalarSol
#define Get_solSize                   	 MMG5_Get_solSize
#define Get_tetrahedron               	 MMG5_Get_tetrahedron
#define Get_triangle                  	 MMG5_Get_triangle
#define Get_vertex                    	 MMG5_Get_vertex
#define HGeom                         	 MMG5_HGeom
#define Info                          	 MMG5_Info
#define Init_fileNames                	 MMG5_Init_fileNames
#define Init_fileNames                	 MMG5_Init_fileNames
#define Init_mesh                     	 MMG5_Init_mesh
#define Init_mesh                     	 MMG5_Init_mesh
#define Init_parameters               	 MMG5_Init_parameters
#define Mesh                          	 MMG5_Mesh
#define Par                           	 MMG5_Par
#define Point                         	 MMG5_Point
#define Set_corner                    	 MMG5_Set_corner
#define Set_dparameter                	 MMG5_Set_dparameter
#define Set_edge                      	 MMG5_Set_edge
#define Set_handGivenMesh             	 MMG5_Set_handGivenMesh
#define Set_inputMeshName             	 MMG5_Set_inputMeshName
#define Set_inputSingulName           	 MMG5_Set_inputSingulName
#define Set_inputSolName              	 MMG5_Set_inputSolName
#define Set_iparameter                	 MMG5_Set_iparameter
#define Set_localParameter            	 MMG5_Set_localParameter
#define Set_meshSize                  	 MMG5_Set_meshSize
#define Set_outputMeshName            	 MMG5_Set_outputMeshName
#define Set_outputSolName             	 MMG5_Set_outputSolName
#define Set_requiredEdge              	 MMG5_Set_requiredEdge
#define Set_requiredTetrahedron       	 MMG5_Set_requiredTetrahedron
#define Set_requiredTriangle          	 MMG5_Set_requiredTriangle
#define Set_requiredVertex            	 MMG5_Set_requiredVertex
#define Set_ridge                     	 MMG5_Set_ridge
#define Set_saveFunc                  	 MMG5_Set_saveFunc
#define Set_scalarSol                 	 MMG5_Set_scalarSol
#define Set_singulCorner              	 MMG5_Set_singulCorner
#define Set_singulEdge                	 MMG5_Set_singulEdge
#define Set_singulRequiredEdge        	 MMG5_Set_singulRequiredEdge
#define Set_singulRequiredVertex      	 MMG5_Set_singulRequiredVertex
#define Set_singulRidge               	 MMG5_Set_singulRidge
#define Set_singulSize                	 MMG5_Set_singulSize
#define Set_singulVertex              	 MMG5_Set_singulVertex
#define Set_solSize                   	 MMG5_Set_solSize
#define Set_tetrahedron               	 MMG5_Set_tetrahedron
#define Set_triangle                  	 MMG5_Set_triangle
#define Set_vertex                    	 MMG5_Set_vertex
#define Singul                        	 MMG5_Singul
#define Sol                           	 MMG5_Sol
#define Tetra                         	 MMG5_Tetra
#define Tria                          	 MMG5_Tria
#define destockOptions                	 MMG5_destockOptions
#define hgeom                         	 MMG5_hgeom
#define loadMesh                      	 MMG5_loadMesh
#define loadMet                       	 MMG5_loadMet
#define loadSingul                    	 MMG5_loadSingul
#define mmg3dcheck                    	 MMG5_mmg3dcheck
#define mmg3dcheck                    	 MMG5_mmg3dcheck
#define mmg3dlib                      	 MMG5_mmg3dlib
#define mmg3dlib                      	 MMG5_mmg3dlib
#define pEdge                         	 MMG5_pEdge
#define pMesh                         	 MMG5_pMesh
#define pPar                          	 MMG5_pPar
#define pPoint                        	 MMG5_pPoint
#define pSingul                       	 MMG5_pSingul
#define pSol                          	 MMG5_pSol
#define pTetra                        	 MMG5_pTetra
#define pTria                         	 MMG5_pTria
#define pampa_setfunc                 	 MMG5_pampa_setfunc
#define parsar                        	 MMG5_parsar
#define parsar                        	 MMG5_parsar
#define parsop                        	 MMG5_parsop
#define psPoint                       	 MMG5_psPoint
#define pxPoint                       	 MMG5_pxPoint
#define pxTetra                       	 MMG5_pxTetra
#define sPoint                        	 MMG5_sPoint
#define saveMet                       	 MMG5_saveMet
#define searchlen                     	 MMG5_searchlen
#define searchqua                     	 MMG5_searchqua
#define setfunc                       	 MMG5_setfunc
#define stockOptions                  	 MMG5_stockOptions
#define usage                         	 MMG5_usage
#define xPoint                        	 MMG5_xPoint
#define xTetra                        	 MMG5_xTetra
