/*
**
** This file is part of Mmg3d.
**
*/
/****************************************
 * genheader.c
 *
 * generate an executable to generate
 * headers for Fortran Mmg3d5 users.
 * Used by makefile
 ****************************************/

#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>

/*
  Program: genheader

  Generate headers (for fortran) setting MMG5_DATA_PTR
  macro to the correct value.

  Parameters:
  argc - must be 3
  argv - contains the names wanted for the Fortran header

  Returns:
  EXIT_SUCCESS

*/
int main (int argc, char ** argv)
{
  char * header_f  = NULL;
  char * libmmg_h  = NULL;
  char * genfort   = NULL;
  char * cmd       = NULL;
  FILE * file      = NULL;

  if (argc != 4)
    {
      fprintf(stderr, "usage : %s headerNameFortran.h libmmg3d5.h"
              " genfort.pl\n",argv[0]);
      return EXIT_FAILURE;
    }

  header_f  = argv[1];
  libmmg_h  = argv[2];
  genfort   = argv[3];

  /* Fortran header */
  file = fopen (header_f,"w");

  if ( file == NULL )
    return(EXIT_FAILURE);

  fprintf(file,"/** This file is automatically generated by the \"genheader.c\" code ");
  fprintf(file,"and the \"genfort.pl\" script (../Scripts).*/\n");
  fprintf(file,"/** Do not modified it by hand, it will be discarded.*/\n");
  fprintf(file,"/** Note: \"genfort.pl\" is automatically called by the ");
  fprintf(file,"\"genheader.c\" executable code.*/\n\n");

  /* Compute the size of the C pointer for the Fortran programm */
  fprintf(file, "#define MMG5_DATA_PTR_T INTEGER(kind=%d)\n\n",
	  (int)sizeof(void*));

  fclose(file);

  /* Generate Fortran header */
  if (NULL == (cmd = (char*)malloc((strlen(genfort)+
				    strlen(libmmg_h)+
				    strlen(header_f)+128)*sizeof(char))))
    return EXIT_FAILURE;
  sprintf(cmd, "perl %s -f %s >> %s;",
	  genfort, libmmg_h, header_f);
  fprintf(stdout, "%s\n", cmd);
  if (-1 == system(cmd))
    return EXIT_FAILURE;
  free(cmd);

  return(0);
}
